site_name: Docker Volume Driver for vSphere
pages:
    - Home: index.md
    - Installation and Deployment: user-guide/install.md
    - Features:
        - Tenancy: features/tenancy.md
        - VSAN Policy: features/vsan-policy.md
        - Integration with vCenter: features/vcenter.md
    - User Guide:
        - Docker Volume CLI:
            - Basic commands: user-guide/docker-volume-cli.md
            - Multiple Datastores: user-guide/datastores.md
        - Backend ESX Overview:
            - Volume Layout: user-guide/esx-overview.md
        - Admin CLI: user-guide/admin-cli.md
    - FAQ: user-guide/faq.md
    - Blog:
        - 2016:
            - September:
                - Release announcement and updates: blog/2016-9-28.md
            - October:
                - 0.8.1 Release (Tenancy) and stateful containers meetup: blog/2016-10-28.md
theme: readthedocs
google_analytics: ['UA-81413942-1', 'https://vmware.github.io/docker-volume-vsphere/']
site_favicon: favicon.ico
site_author: cna-storage@vmware.com
site_url: https://vmware.github.io/docker-volume-vsphere/
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - fenced_code
